/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class UDPStreamerJNI */

#ifndef _Included_UDPStreamerJNI
#define _Included_UDPStreamerJNI
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     UDPStreamerJNI
 * Method:    native_blocking_receive
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_UDPStreamerJNI_native_1blocking_1receive
  (JNIEnv *, jobject);

/*
 * Class:     UDPStreamerJNI
 * Method:    native_send
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_UDPStreamerJNI_native_1send
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
